import { createFileRoute } from "@tanstack/react-router";
import { FeatureShell } from "../components/FeatureShell";
import { FileText, Download } from "lucide-react";

export const Route = createFileRoute("/dashboard/reports")({
  head: () => ({ meta: [{ title: "Reports & Insights — Bharat Climate Twin" }] }),
  component: Reports,
});

const reports = [
  { title: "Pre-monsoon outlook · 2026", region: "All-India", date: "Mar 2026", pages: 28 },
  { title: "Kharif risk briefing", region: "Maharashtra", date: "Feb 2026", pages: 14 },
  { title: "Coastal cyclone vulnerability", region: "Odisha & Andhra", date: "Jan 2026", pages: 22 },
  { title: "District heat-stress profile", region: "Rajasthan", date: "Jan 2026", pages: 18 },
  { title: "Hydrological outlook · Brahmaputra", region: "Assam", date: "Dec 2025", pages: 20 },
];

function Reports() {
  return (
    <FeatureShell
      eyebrow="Reports"
      title="Plain-language briefings, ready to download."
      description="Curated district-level reports generated by the Climate Twin pipeline. Each one is a single PDF you can hand to anyone."
    >
      <div className="overflow-hidden rounded-3xl glass-strong">
        <ul className="divide-y divide-white/10">
          {reports.map((r) => (
            <li key={r.title} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 px-5 py-4 transition-colors hover:bg-white/5 sm:grid-cols-[auto_1fr_auto_auto]">
              <span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-teal/15 to-monsoon/10 text-teal">
                <FileText className="h-4 w-4" />
              </span>
              <div className="min-w-0">
                <p className="truncate font-display text-sm font-semibold">{r.title}</p>
                <p className="truncate text-xs text-muted-foreground">{r.region} · {r.pages} pages</p>
              </div>
              <span className="hidden font-mono text-[11px] text-muted-foreground sm:block">{r.date}</span>
              <button className="inline-flex items-center gap-1.5 rounded-full glass-btn px-3.5 py-2 text-xs font-semibold transition-transform hover:scale-[1.04]">
                <Download className="h-3.5 w-3.5" /> PDF
              </button>
            </li>
          ))}
        </ul>
      </div>
    </FeatureShell>
  );
}
