import { createFileRoute } from "@tanstack/react-router";
import { FeatureShell } from "../components/FeatureShell";
import { FileText, Download } from "lucide-react";

export const Route = createFileRoute("/dashboard/reports")({
  head: () => ({ meta: [{ title: "Reports & Insights — Bharat Climate Twin" }] }),
  component: Reports,
});

const reports = [
  { title: "Pre-Monsoon Outlook 2026", region: "All-India", date: "Mar 2026", pages: 28 },
  { title: "Kharif Risk Briefing", region: "Maharashtra", date: "Feb 2026", pages: 14 },
  { title: "Coastal Cyclone Vulnerability", region: "Odisha & Andhra", date: "Jan 2026", pages: 22 },
  { title: "District Heat-Stress Profile", region: "Rajasthan", date: "Jan 2026", pages: 18 },
  { title: "Hydrological Outlook — Brahmaputra", region: "Assam", date: "Dec 2025", pages: 20 },
];

function Reports() {
  return (
    <FeatureShell
      eyebrow="Reports"
      title="Reports & Insights"
      description="Curated, district-level climate briefings generated by the Bharat Climate Twin pipeline. Downloadable as PDF."
    >
      <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-card">
        <ul className="divide-y divide-border">
          {reports.map((r) => (
            <li key={r.title} className="grid grid-cols-[auto_1fr_auto] items-center gap-4 px-5 py-4 transition-colors hover:bg-muted/50 sm:grid-cols-[auto_1fr_auto_auto]">
              <span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-accent text-teal">
                <FileText className="h-4 w-4" />
              </span>
              <div className="min-w-0">
                <p className="truncate font-display text-sm font-semibold">{r.title}</p>
                <p className="truncate text-xs text-muted-foreground">{r.region} · {r.pages} pages</p>
              </div>
              <span className="hidden text-xs font-medium text-muted-foreground sm:block">{r.date}</span>
              <button className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs font-semibold text-foreground transition-colors hover:bg-accent">
                <Download className="h-3.5 w-3.5" /> PDF
              </button>
            </li>
          ))}
        </ul>
      </div>
    </FeatureShell>
  );
}
